### ISSUE TITLE
Can a list contain a single item?

### ISSUE THREAD

**Issue by dyacob** [w3c/elreq#113]
A rule of list formation taught for some some languages requires that an ordered list must contain more than a single item.  That is a list, cannot contain only an "A)" or 1." entry, and must also containing at least a "B)" or "2.".  Otherwise another layout approach must be applied.

Question: Do Ethiopic list formation rules allow for a single item?  If a list reduces to a single entry, what alternative layout should be applied?

**Comment by dyacob** [comment]
Examples were found where a single item list would be valid
(see: https://lists.w3.org/Archives/Public/public-i18n-ethiopic/2018AprJun/0004.html).  However, the topic was deemed out of scope and more appropriate for a style guide.

**Comment by r12a** [comment]
For convenience, here's a link corresponding to the one above that shows the whole thread, and is therefore easier to read.
https://www.w3.org/Mail/flatten/index?subject=Is+a+list+of+one+item+still+a+list&list=public-i18n-ethiopic
