### ISSUE TITLE
Use a webfont

### ISSUE THREAD

**Issue by r12a** [w3c/elreq#88]
I noticed that the ethiopic text wasn't showing up on my iPad.  I suggest we include the google noto ethiopic font as a webfont bundled with the page.

**Comment by dyacob** [comment]
This is a good idea, I'll look into how this is done.  The font that I develop the document with on my end is Abyssinica SIL.  Is a note with font recommendation appropriate for layout requirement documents?

**Comment by r12a** [comment]
if you include abyssinic SIL as a webfont, you won't need to add a note.  If you are struggling to add it, let me know and i'll help.  Main thing is to check that we can put a copy of A SIL on our website - i think the SIL licence does permit that, but we need to check.

**Comment by dyacob** [comment]
Richard,  the SIL provides a webfont for Abyssinica and I've added it to the project and included it from the index.html.  Please check that it works on your end.

**Comment by r12a** [comment]
i don't think we should apply the abyssinica font to the body – we may have a problem with the webmaster on that.  I suggest we just have a rule that says something like `:lang(am), :lang(ti) <etc> { font-family: "Abyssinica SIL", AbyssinicaSILW, sans-serif; }` and make sure that all ethiopic text has a lang attribute (or some other class name).  Make sense?

**Comment by r12a** [comment]
and actually, it doesn't work on my end anyway.  The style rule is blocked.

**Comment by dyacob** [comment]
I need to take you up on the offer to help :-)  I've tried some changes but am struggling to get the CSS to flow right.  Please have a look when you have a moment, I'll keep my hands off this area.

**Comment by r12a** [comment]
Daniel, i think you have the CSS ok, you just need to add `lang` attributes to the tags that contain ethiopic text.   (In some cases you'll need to add tags (which will also force you to fix some places where you used `br` instead of `p` tags too ;) )).  If you need help with that, let me know.

**Comment by dyacob** [comment]
spans and lang attributes are added most everywhere.  closing the issue now though a still characters may have slipped through the cracks and will be addressed as discovered.
