### ISSUE TITLE
Add a section on punctuation

### ISSUE THREAD

**Issue by r12a** [w3c/elreq#89]
I think it would be helpful to have a subsection near the beginning of the  "Characters" section that describes ethiopic punctuation and its use.  The section could start with a list of punctuation used, and descriptions of the non-ASCII/ANSI stuff and how it is used.  For example, where is U+1362   ETHIOPIC FULL STOP ። used, how common is it, does it have spaces before/after, etc.?

This punctuation section could also harbour most of the current section 2.2 Latin punctuation with Ethiopic, which is actually about more than Latin punctuation anyway, and 6.2.3 Ethiopic Comma Usage and probably the four following subsections.

**Comment by dyacob** [comment]
Completed with commit 1928db083388d191aa187dafd774898b3333a6e2
