### ISSUE TITLE
Word splitting

### ISSUE THREAD

**Issue by r12a** [w3c/elreq#94]
3.2 Hyphenation
http://w3c.github.io/elreq/#ethiopic_hyphenation

> A word is split at a location where the user would not be able to infer from context whether one or two words appears across lines. I.E. a split should not occur at the boundary of a compound word.
> 
> Words are split along a syllable boundary.

it wasn't clear to me how those two bullet points are reconciled with each other.

**Comment by dyacob** [comment]
This is effectively addressed by commit b7ef3dea96ba50219ae0c13653445367d3531233 which revises the rule list -which is now synced with updates in the survey document.
