### ISSUE TITLE
'Word-bounded' or 'word-bound' ?

### ISSUE THREAD

**Issue by r12a** [w3c/elreq#95]
3.6.3 Justification with Word Bounded Wordspace and Punctuation
http://w3c.github.io/elreq/#justification_with_word_bounded_wordspace

> referred to here as “word bounded”

'word bounded' suggests to me boundaries and wrapping, whereas 'word-bound' suggests sticking to a word.  Is 'word-bounded' the standard term, or should we consider changing it?

**Comment by dyacob** [comment]
There is no standard term, "word bounded" was coined in the course of writing the spec, an earlier draft used the description "left bounded".  Sticking to a word is the intended meaning to communicate here, thus "Word bound" is an appropriate change.
