### ISSUE TITLE
Additional spaces in justification

### ISSUE THREAD

**Issue by r12a** [w3c/elreq#97]
3.6.4 Justification with Centered Wordspace and Punctuation
http://w3c.github.io/elreq/#justification_with_centered_wordspace

Do people sometimes insert spaces into text to help with justification?  If so, should the justification process ignore or remove them?

**Comment by dyacob** [comment]
Yes, space is sometimes inserted around Ethiopic wordspace as a work-around to trick software into justifying text closer to expectations.  Future software that is "wordspace aware" could ignore these spaces during justification.  Unless the spaces are acceptable under a rule given in Section 2.5.1 Rules of Applying Whitespace in Ethiopic Text (http://w3c.github.io/elreq/#ethiopic_whitespace_rules).

I'll add a note to 3.6.4 to clarify how spaces should be treated during justification.
