### ISSUE TITLE
Is / a counter suffix?

### ISSUE THREAD

**Issue by r12a** [w3c/elreq#98]
3.7.2 Ordered List Item Marker
http://w3c.github.io/elreq/#list_item_marker

the following section has an example that uses / as a counter suffix.  Is this another alternative?  It's not listed in this section.

**Comment by dyacob** [comment]
Good catch!  This is fixed now in commit c897ccb3660da5a28954ac2319b6ef3c6986c6c2 .

A follow up question:  Is "Counter Suffix" a more conventional name to use than "List Item Marker"?  I had learned "list item marker" in the early 2000s, I think it was the name Mozilla developers were using at the time.

**Comment by r12a** [comment]
It is called a counter style suffix in the CSS Counter Styles spec, so maybe we should use it for that reason. The CSS spec describes the suffix as "a <symbol> that is appended to the marker representation", thereby making a distinction between the marker and the suffix. See https://www.w3.org/TR/css-counter-styles-3/#counter-style-suffix
